services:
  postgres:
    image: postgres:16-alpine
    container_name: cpf_postgres

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"

    volumes:
    - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .

    container_name: cpf_backend

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    command: >
      sh -c "
      python -m app.scripts.seed &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
volumes:
  postgres_data: